FROM tensorflow/tensorflow:latest-gpu
LABEL name='JUPYTER LAB CUDA TensorFlow + Pytorch' version=1
RUN apt update && apt install -y  git
WORKDIR /code
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
COPY /requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir -r /code/requirements.txt
RUN pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116
COPY ./ /code